version: '3'
services:
  app:
    build: .
    ports:
      - 3000:3000
  nginx:
    image: nginx:1.22
    depends_on:
      - app
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt/archive/semas.godata.id:/etc/letsencrypt/live/semas.godata.id